package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strconv"
	"text/template"
)

func generateCode(path string, envs []Env) error {
	functions := template.FuncMap{
		"constName": constName,
		"fieldName": fieldName,
		"anyFile": func(envs []Env) bool {
			for _, env := range envs {
				if env.File {
					return true
				}
			}
			return false
		},
		"parseFunc": func(goType string) string {
			if goType == "string" {
				return "toString"
			}
			return "to" + goType
		},
		"defaultValue": func(value *string) string {
			return *value
		},
		"quote": strconv.Quote,
	}
	tmpl, err := template.New("config").Funcs(functions).Parse(codeTemplate)
	if err != nil {
		return err
	}
	var buffer bytes.Buffer
	if err := tmpl.Execute(&buffer, envs); err != nil {
		return err
	}
	generated, err := format.Source(buffer.Bytes())
	if err != nil {
		return fmt.Errorf("format generated code: %w\n%s", err, buffer.String())
	}
	if err := os.WriteFile(path, generated, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

const codeTemplate = `// Code generated by configs/generate; DO NOT EDIT.

package configs

import (
	"errors"
	"fmt"
{{- if anyFile . }}
	"os"
	"strings"
{{- end }}

	"github.com/spf13/viper"
)

var ErrNotDefined = errors.New("variable not defined")

func init() {
	viper.AutomaticEnv()
}

const (
{{- range . }}
	{{ constName .Name }} = {{ quote .Name }}
{{- if .File }}
	{{ constName .Name }}_FILE = {{ quote (printf "%s_FILE" .Name) }}
{{- end }}
{{- end }}
)

func SetDefaults() {
{{- range . }}
	viper.SetDefault({{ constName .Name }}, {{ quote (defaultValue .Default) }})
{{- end }}
}

type MateConfig struct {
{{- range . }}
	{{ fieldName .Name }} {{ .GoType }}
{{- end }}
}

func LoadMateConfig() (*MateConfig, error) {
	SetDefaults()
	var cfg MateConfig
	var err error
{{ range . }}
	cfg.{{ fieldName .Name }}, err = Get{{ fieldName .Name }}()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", {{ constName .Name }}, err)
	}
{{ end }}
	return &cfg, nil
}

{{ range . }}
func Get{{ fieldName .Name }}() ({{ .GoType }}, error) {
	value := viper.GetString({{ constName .Name }})
{{- if .File }}
	if value == "" {
		if filename := viper.GetString({{ constName .Name }}_FILE); filename != "" {
			contents, err := os.ReadFile(filename)
			if err != nil {
				return notDefined{{ .GoType }}(), fmt.Errorf("failed to read %s: %w", {{ constName .Name }}_FILE, err)
			}
			value = strings.TrimSpace(string(contents))
		}
	}
{{- end }}
	if value != "" {
		parsed, err := {{ parseFunc .GoType }}(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", {{ constName .Name }}, err)
		}
		return parsed, nil
	}
	return notDefined{{ .GoType }}(), fmt.Errorf("%s: %w", {{ constName .Name }}, ErrNotDefined)
}
{{ end }}
`
