package main

import (
	"fmt"
	"os"
	"strings"
)

func generateDocs(path string, envs []Env) error {
	var output strings.Builder
	output.WriteString("<!-- Code generated by configs/generate; DO NOT EDIT. -->\n\n")
	output.WriteString("# Mate configuration\n\n")
	for _, env := range envs {
		fmt.Fprintf(&output, "## `%s`\n\n%s\n\n", env.Name, env.Description)
		fmt.Fprintf(&output, "- Type: `%s`\n", env.GoType)
		fmt.Fprintf(&output, "- Default: `%s`\n", *env.Default)
		fmt.Fprintf(&output, "- Used by: `%s`\n\n", strings.Join(env.UsedBy, "`, `"))
	}
	if err := os.MkdirAll("../docs", 0o755); err != nil {
		return err
	}
	content := strings.TrimRight(output.String(), "\n") + "\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
