// Code generated by configs/generate; DO NOT EDIT.

package configs

import (
	"errors"
	"fmt"

	"github.com/spf13/viper"
)

var ErrNotDefined = errors.New("variable not defined")

func init() {
	viper.AutomaticEnv()
}

const (
	ANKI_DECK     = "MATE_ANKI_DECK"
	ANKI_ENDPOINT = "MATE_ANKI_ENDPOINT"
	CODEX_BIN     = "MATE_CODEX_BIN"
	LOG_COLOR     = "MATE_LOG_COLOR"
	LOG_LEVEL     = "MATE_LOG_LEVEL"
	OUTPUT_DIR    = "MATE_OUTPUT_DIR"
	STUDY_DIR     = "MATE_STUDY_DIR"
	DPI           = "MATE_DPI"
	STATE_DB      = "MATE_STATE_DB"
)

func SetDefaults() {
	viper.SetDefault(ANKI_DECK, "Mate")
	viper.SetDefault(ANKI_ENDPOINT, "http://127.0.0.1:8765")
	viper.SetDefault(CODEX_BIN, "codex")
	viper.SetDefault(LOG_COLOR, "true")
	viper.SetDefault(LOG_LEVEL, "info")
	viper.SetDefault(OUTPUT_DIR, "~/.mate/output")
	viper.SetDefault(STUDY_DIR, "~/GoodNotes")
	viper.SetDefault(DPI, "250")
	viper.SetDefault(STATE_DB, "~/.mate/state.db")
}

type MateConfig struct {
	AnkiDeck     string
	AnkiEndpoint string
	CodexBin     string
	LogColor     Bool
	LogLevel     LogLevel
	OutputDir    Path
	StudyDir     Path
	DPI          RenderDPI
	StateDB      Path
}

func LoadMateConfig() (*MateConfig, error) {
	SetDefaults()
	var cfg MateConfig
	var err error

	cfg.AnkiDeck, err = GetAnkiDeck()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", ANKI_DECK, err)
	}

	cfg.AnkiEndpoint, err = GetAnkiEndpoint()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", ANKI_ENDPOINT, err)
	}

	cfg.CodexBin, err = GetCodexBin()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", CODEX_BIN, err)
	}

	cfg.LogColor, err = GetLogColor()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", LOG_COLOR, err)
	}

	cfg.LogLevel, err = GetLogLevel()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", LOG_LEVEL, err)
	}

	cfg.OutputDir, err = GetOutputDir()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", OUTPUT_DIR, err)
	}

	cfg.StudyDir, err = GetStudyDir()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", STUDY_DIR, err)
	}

	cfg.DPI, err = GetDPI()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", DPI, err)
	}

	cfg.StateDB, err = GetStateDB()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", STATE_DB, err)
	}

	return &cfg, nil
}

func GetAnkiDeck() (string, error) {
	value := viper.GetString(ANKI_DECK)
	if value != "" {
		parsed, err := toString(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", ANKI_DECK, err)
		}
		return parsed, nil
	}
	return notDefinedstring(), fmt.Errorf("%s: %w", ANKI_DECK, ErrNotDefined)
}

func GetAnkiEndpoint() (string, error) {
	value := viper.GetString(ANKI_ENDPOINT)
	if value != "" {
		parsed, err := toString(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", ANKI_ENDPOINT, err)
		}
		return parsed, nil
	}
	return notDefinedstring(), fmt.Errorf("%s: %w", ANKI_ENDPOINT, ErrNotDefined)
}

func GetCodexBin() (string, error) {
	value := viper.GetString(CODEX_BIN)
	if value != "" {
		parsed, err := toString(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", CODEX_BIN, err)
		}
		return parsed, nil
	}
	return notDefinedstring(), fmt.Errorf("%s: %w", CODEX_BIN, ErrNotDefined)
}

func GetLogColor() (Bool, error) {
	value := viper.GetString(LOG_COLOR)
	if value != "" {
		parsed, err := toBool(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", LOG_COLOR, err)
		}
		return parsed, nil
	}
	return notDefinedBool(), fmt.Errorf("%s: %w", LOG_COLOR, ErrNotDefined)
}

func GetLogLevel() (LogLevel, error) {
	value := viper.GetString(LOG_LEVEL)
	if value != "" {
		parsed, err := toLogLevel(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", LOG_LEVEL, err)
		}
		return parsed, nil
	}
	return notDefinedLogLevel(), fmt.Errorf("%s: %w", LOG_LEVEL, ErrNotDefined)
}

func GetOutputDir() (Path, error) {
	value := viper.GetString(OUTPUT_DIR)
	if value != "" {
		parsed, err := toPath(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", OUTPUT_DIR, err)
		}
		return parsed, nil
	}
	return notDefinedPath(), fmt.Errorf("%s: %w", OUTPUT_DIR, ErrNotDefined)
}

func GetStudyDir() (Path, error) {
	value := viper.GetString(STUDY_DIR)
	if value != "" {
		parsed, err := toPath(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", STUDY_DIR, err)
		}
		return parsed, nil
	}
	return notDefinedPath(), fmt.Errorf("%s: %w", STUDY_DIR, ErrNotDefined)
}

func GetDPI() (RenderDPI, error) {
	value := viper.GetString(DPI)
	if value != "" {
		parsed, err := toRenderDPI(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", DPI, err)
		}
		return parsed, nil
	}
	return notDefinedRenderDPI(), fmt.Errorf("%s: %w", DPI, ErrNotDefined)
}

func GetStateDB() (Path, error) {
	value := viper.GetString(STATE_DB)
	if value != "" {
		parsed, err := toPath(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", STATE_DB, err)
		}
		return parsed, nil
	}
	return notDefinedPath(), fmt.Errorf("%s: %w", STATE_DB, ErrNotDefined)
}
