// Code generated by configs/generate; DO NOT EDIT.

package configs

import (
	"errors"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/viper"
)

var ErrNotDefined = errors.New("variable not defined")

func init() {
	viper.AutomaticEnv()
}

const (
	ANKI_DECK             = "MATE_ANKI_DECK"
	ANKI_ENDPOINT         = "MATE_ANKI_ENDPOINT"
	LLM_API_KEY           = "MATE_LLM_API_KEY"
	LLM_API_KEY_FILE      = "MATE_LLM_API_KEY_FILE"
	LLM_BASE_URL          = "MATE_LLM_BASE_URL"
	LLM_MODEL             = "MATE_LLM_MODEL"
	LLM_TIMEOUT_SECONDS   = "MATE_LLM_TIMEOUT_SECONDS"
	LOG_COLOR             = "MATE_LOG_COLOR"
	LOG_LEVEL             = "MATE_LOG_LEVEL"
	NOTIFICATIONS         = "MATE_NOTIFICATIONS"
	OUTPUT_DIR            = "MATE_OUTPUT_DIR"
	STUDY_DIR             = "MATE_STUDY_DIR"
	POLL_INTERVAL_SECONDS = "MATE_POLL_INTERVAL_SECONDS"
	DPI                   = "MATE_DPI"
	STATE_DB              = "MATE_STATE_DB"
)

func SetDefaults() {
	viper.SetDefault(ANKI_DECK, "Mate")
	viper.SetDefault(ANKI_ENDPOINT, "http://127.0.0.1:8765")
	viper.SetDefault(LLM_API_KEY, "")
	viper.SetDefault(LLM_BASE_URL, "https://api.openai.com/v1")
	viper.SetDefault(LLM_MODEL, "gpt-5.1")
	viper.SetDefault(LLM_TIMEOUT_SECONDS, "600")
	viper.SetDefault(LOG_COLOR, "true")
	viper.SetDefault(LOG_LEVEL, "info")
	viper.SetDefault(NOTIFICATIONS, "true")
	viper.SetDefault(OUTPUT_DIR, "~/.mate/output")
	viper.SetDefault(STUDY_DIR, "~/GoodNotes")
	viper.SetDefault(POLL_INTERVAL_SECONDS, "900")
	viper.SetDefault(DPI, "250")
	viper.SetDefault(STATE_DB, "~/.mate/state.db")
}

type MateConfig struct {
	AnkiDeck            string
	AnkiEndpoint        string
	LLMAPIKey           RedactedString
	LLMBaseURL          string
	LLMModel            string
	LLMTimeoutSeconds   Seconds
	LogColor            Bool
	LogLevel            LogLevel
	Notifications       Bool
	OutputDir           Path
	StudyDir            Path
	PollIntervalSeconds Seconds
	DPI                 RenderDPI
	StateDB             Path
}

func LoadMateConfig() (*MateConfig, error) {
	SetDefaults()
	var cfg MateConfig
	var err error

	cfg.AnkiDeck, err = GetAnkiDeck()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", ANKI_DECK, err)
	}

	cfg.AnkiEndpoint, err = GetAnkiEndpoint()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", ANKI_ENDPOINT, err)
	}

	cfg.LLMAPIKey, err = GetLLMAPIKey()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", LLM_API_KEY, err)
	}

	cfg.LLMBaseURL, err = GetLLMBaseURL()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", LLM_BASE_URL, err)
	}

	cfg.LLMModel, err = GetLLMModel()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", LLM_MODEL, err)
	}

	cfg.LLMTimeoutSeconds, err = GetLLMTimeoutSeconds()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", LLM_TIMEOUT_SECONDS, err)
	}

	cfg.LogColor, err = GetLogColor()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", LOG_COLOR, err)
	}

	cfg.LogLevel, err = GetLogLevel()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", LOG_LEVEL, err)
	}

	cfg.Notifications, err = GetNotifications()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", NOTIFICATIONS, err)
	}

	cfg.OutputDir, err = GetOutputDir()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", OUTPUT_DIR, err)
	}

	cfg.StudyDir, err = GetStudyDir()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", STUDY_DIR, err)
	}

	cfg.PollIntervalSeconds, err = GetPollIntervalSeconds()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", POLL_INTERVAL_SECONDS, err)
	}

	cfg.DPI, err = GetDPI()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", DPI, err)
	}

	cfg.StateDB, err = GetStateDB()
	if err != nil {
		return nil, fmt.Errorf("failed to get %s: %w", STATE_DB, err)
	}

	return &cfg, nil
}

func GetAnkiDeck() (string, error) {
	value := viper.GetString(ANKI_DECK)
	if value != "" {
		parsed, err := toString(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", ANKI_DECK, err)
		}
		return parsed, nil
	}
	return notDefinedstring(), fmt.Errorf("%s: %w", ANKI_DECK, ErrNotDefined)
}

func GetAnkiEndpoint() (string, error) {
	value := viper.GetString(ANKI_ENDPOINT)
	if value != "" {
		parsed, err := toString(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", ANKI_ENDPOINT, err)
		}
		return parsed, nil
	}
	return notDefinedstring(), fmt.Errorf("%s: %w", ANKI_ENDPOINT, ErrNotDefined)
}

func GetLLMAPIKey() (RedactedString, error) {
	value := viper.GetString(LLM_API_KEY)
	if value == "" {
		if filename := viper.GetString(LLM_API_KEY_FILE); filename != "" {
			contents, err := os.ReadFile(filename)
			if err != nil {
				return notDefinedRedactedString(), fmt.Errorf("failed to read %s: %w", LLM_API_KEY_FILE, err)
			}
			value = strings.TrimSpace(string(contents))
		}
	}
	if value != "" {
		parsed, err := toRedactedString(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", LLM_API_KEY, err)
		}
		return parsed, nil
	}
	return notDefinedRedactedString(), fmt.Errorf("%s: %w", LLM_API_KEY, ErrNotDefined)
}

func GetLLMBaseURL() (string, error) {
	value := viper.GetString(LLM_BASE_URL)
	if value != "" {
		parsed, err := toString(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", LLM_BASE_URL, err)
		}
		return parsed, nil
	}
	return notDefinedstring(), fmt.Errorf("%s: %w", LLM_BASE_URL, ErrNotDefined)
}

func GetLLMModel() (string, error) {
	value := viper.GetString(LLM_MODEL)
	if value != "" {
		parsed, err := toString(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", LLM_MODEL, err)
		}
		return parsed, nil
	}
	return notDefinedstring(), fmt.Errorf("%s: %w", LLM_MODEL, ErrNotDefined)
}

func GetLLMTimeoutSeconds() (Seconds, error) {
	value := viper.GetString(LLM_TIMEOUT_SECONDS)
	if value != "" {
		parsed, err := toSeconds(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", LLM_TIMEOUT_SECONDS, err)
		}
		return parsed, nil
	}
	return notDefinedSeconds(), fmt.Errorf("%s: %w", LLM_TIMEOUT_SECONDS, ErrNotDefined)
}

func GetLogColor() (Bool, error) {
	value := viper.GetString(LOG_COLOR)
	if value != "" {
		parsed, err := toBool(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", LOG_COLOR, err)
		}
		return parsed, nil
	}
	return notDefinedBool(), fmt.Errorf("%s: %w", LOG_COLOR, ErrNotDefined)
}

func GetLogLevel() (LogLevel, error) {
	value := viper.GetString(LOG_LEVEL)
	if value != "" {
		parsed, err := toLogLevel(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", LOG_LEVEL, err)
		}
		return parsed, nil
	}
	return notDefinedLogLevel(), fmt.Errorf("%s: %w", LOG_LEVEL, ErrNotDefined)
}

func GetNotifications() (Bool, error) {
	value := viper.GetString(NOTIFICATIONS)
	if value != "" {
		parsed, err := toBool(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", NOTIFICATIONS, err)
		}
		return parsed, nil
	}
	return notDefinedBool(), fmt.Errorf("%s: %w", NOTIFICATIONS, ErrNotDefined)
}

func GetOutputDir() (Path, error) {
	value := viper.GetString(OUTPUT_DIR)
	if value != "" {
		parsed, err := toPath(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", OUTPUT_DIR, err)
		}
		return parsed, nil
	}
	return notDefinedPath(), fmt.Errorf("%s: %w", OUTPUT_DIR, ErrNotDefined)
}

func GetStudyDir() (Path, error) {
	value := viper.GetString(STUDY_DIR)
	if value != "" {
		parsed, err := toPath(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", STUDY_DIR, err)
		}
		return parsed, nil
	}
	return notDefinedPath(), fmt.Errorf("%s: %w", STUDY_DIR, ErrNotDefined)
}

func GetPollIntervalSeconds() (Seconds, error) {
	value := viper.GetString(POLL_INTERVAL_SECONDS)
	if value != "" {
		parsed, err := toSeconds(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", POLL_INTERVAL_SECONDS, err)
		}
		return parsed, nil
	}
	return notDefinedSeconds(), fmt.Errorf("%s: %w", POLL_INTERVAL_SECONDS, ErrNotDefined)
}

func GetDPI() (RenderDPI, error) {
	value := viper.GetString(DPI)
	if value != "" {
		parsed, err := toRenderDPI(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", DPI, err)
		}
		return parsed, nil
	}
	return notDefinedRenderDPI(), fmt.Errorf("%s: %w", DPI, ErrNotDefined)
}

func GetStateDB() (Path, error) {
	value := viper.GetString(STATE_DB)
	if value != "" {
		parsed, err := toPath(value)
		if err != nil {
			return parsed, fmt.Errorf("failed to parse %s: %w", STATE_DB, err)
		}
		return parsed, nil
	}
	return notDefinedPath(), fmt.Errorf("%s: %w", STATE_DB, ErrNotDefined)
}
